blank_issues_enabled: false
contact_links:
  - name: Guides and tutorials for Anchor
    url: https://support.greymass.com
    about: Read our guides and answers to commonly asked questions about Anchor.
  - name: User support for Anchor
    url: https://support.greymass.com/support/tickets/new
    about: Have a question or encountering a problem while using Anchor? Open a support ticket.
