blank_issues_enabled: false
contact_links:
  - name: Greymass Support Ticket
    url: https://support.greymass.com/support/tickets/new
    about: Please submit your issues here
  - name: Greymass Support
    url: https://support.greymass.com
    about: Head over for guides and knowledge base.
