name: Feature Request
description: To propose a new feature for Anchor, please fill out the form below

labels: ["anchor", "enhancement"]
body:
  - type: markdown
    id: welcome
    attributes:
      value: "## Note: Be sure to add the title of your request in the field above."
  - type: markdown
    id: welcome
    attributes:
      value: |
        We appreciate you taking the time create a feature request for Anchor!  We will reach out if need be.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Platform
      description: What platform of Anchor is this intended for?
      options:
        - Desktop (MacOS)
        - Desktop (Windows)
        - Desktop (Linux)
        - iOS
        - Android
        - All
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the change you'd like to see in Anchor
      placeholder: Tell us whats you'd like to see
      value: "Please describe"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives/Workarounds
      description: What workarounds or alternatives have you used/considered?
      value: "Please describe"
    validations:
      required: true       
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the feature you're requesting!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
